server:
  port: 8081

spring:
  application:
    name: kafka-consumer-proto
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/kafkaproto
    schema: public
    username: admin
    password: secret
  flyway:
    user: admin
    password: secret
    schemas: public
    url: jdbc:postgresql://localhost:5432/kafkaproto

management:
  tracing:
    enabled: true
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: http://localhost:9411

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

#logging:
#  level:
#    org:
#      flywaydb: DEBUG
#    db:
#      migration: DEBUG